version: '3'

services:

  nginx:
    build: 
      context: .
      dockerfile: dockerfile.nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app
      

  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh
    command: node index.js
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root  




    
